# Generated by Django 5.1.4 on 2025-01-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoques', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('filial', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=200)),
            ],
        ),
    ]
