# Generated by Django 5.1.4 on 2025-01-10 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoques', '0002_gerente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_filial', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='gerente',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoques.filial'),
        ),
    ]
