# Generated by Django 5.1.4 on 2025-01-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoques', '0003_filial_alter_gerente_email_alter_gerente_filial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=200)),
                ('quantidade_esperada', models.IntegerField(default=0)),
            ],
        ),
    ]
