# Generated by Django 5.1.3 on 2025-01-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoques', '0004_provisao'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='valor_unitario',
            field=models.FloatField(default=0),
        ),
    ]
