# Generated by Django 4.2.20 on 2025-04-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoques', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('senha', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Provisao',
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='filial',
        ),
        migrations.RemoveField(
            model_name='gerente',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='filial',
        ),
        migrations.DeleteModel(
            name='Filial',
        ),
    ]
