# Generated by Django 4.2.20 on 2025-04-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoques', '0008_usuario_delete_provisao_remove_gerente_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gerente',
        ),
        migrations.AddField(
            model_name='estoque',
            name='categoria',
            field=models.CharField(default='Geral', max_length=100),
        ),
        migrations.AddField(
            model_name='estoque',
            name='raridade',
            field=models.CharField(choices=[('comum', 'Comum'), ('incomum', 'Incomum'), ('raro', 'Raro'), ('épico', 'Épico'), ('lendário', 'Lendário')], default='comum', max_length=50),
        ),
        migrations.AddField(
            model_name='estoque',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='gerente',
        ),
    ]
